import { ILocalizationTemplate } from "./template";

export const cs: ILocalizationTemplate = {
    Processing: "Zpracovávám",
    SaveFile: "Uložit soubor",
    ExportToEpub: "Exportovat do EPUB",
    SendToSimon: "Odeslat do aplikace Simon",
    ChooseCover: "Vybrat obálku",
    CoverLabel: "Obálka knihy",
    SplitElementLabel: "Název stylu pro dělení na části",
    IsbnSourcePagesLabel: "ISBN zdroj pro stránkování",
    LoginButton: "Přihlásit se",
    LogoutButton: "Odhlásit se",
    ReallyLogout: "Opravdu se chcete odhlásit?",
    CloseButton: "Zavřít",
    isLogged: "",
    isNotedLogged: "Nepřihlášen",
    LoginDialogTitle: "Přihlášení do aplikace Simon",
    LoginDialogFormInvalid: "Zadejte povinné údaje.",
    LoginDialogInvalidCredentials: "Špatné přihlašovací jméno nebo heslo.",
    LoginDialogDisabled: "Tento účet nemá právo k přihlášení do systému.",
    LoginDialogLockedOut: "Váš účet byl dočasně uzamknut kvůli velkému počtu neúspěšných přihlášení. Vyčkejte, než bude účet automaticky odemknut a zkuste přihlášení znovu.",
    RequestToServerFailed: "Připojení k serveru selhalo.",
    LoginDialogUsername: "Přihlašovací jméno",
    LoginDialogPassword: "Heslo",
    LoginFailed: "Přihlášení neúspěšné. Zkontrolujte zadané údaje.",
    LoginDialogCloseButton: "Zavřít",
    LoginDialogLoginButton: "Přihlásit se",
    ConfirmNotAnchoredImagesEPUB: "V dokumentu se nachází neukotvené obrázky. Doporučujeme je před exportem ukotvit. Přejete si pokračovat v exportu do EPUBU?",
    ConfirmNotAnchoredImagesSendToServer: "V dokumentu se nachází neukotvené obrázky. Doporučujeme je před odesláním ukotvit. Přejete si pokračovat v odesílání do aplikace Simon?",
    NoActiveDocument: "Nejdříve musíte otevřít dokument.",
    ExportSettingsDialogTitle: "Nastavení exportu",
    ExportSettingsDialogCloseButton: "Zavřít",
    ExportSettingsDialogSubmit: "OK",
    CoverImageIsLoading: "Obálka se načítá...",
    UnknownError: "Neznámá chyba",
    ExportFailed: "Export do souboru epub selhal.",
    CannotGetFileForSaving: "Nepodařilo se získat soubor pro uložení",
    CannotCreateTemporaryFileOrFolder: "Nepodařilo se vytvořit dočasný soubor nebo složku",
    CannotReadTemporaryFile: "Nepodařilo se otevřít hotový epub soubor",
    LoginExpired: "Relace pravděpodobně vypršela. Přihlaste se prosím znovu.",
    SendFailedLoginExpired: "Odeslání do aplikace Simon selhalo. Relace pravděpodobně vypršela. Přihlaste se prosím znovu.",
    SendFailed: "Odeslání souboru do aplikace Simon selhalo.",
    SendSuccess: "Soubor byl úspěšně odeslán do aplikace Simon."
};