import { ILocalizationTemplate } from "./template";

export const en: ILocalizationTemplate = {
    Processing: "Processing",
    SaveFile: "Save file",
    ExportToEpub: "Export to ePub",
    SendToSimon: "Send to Simon app",
    ChooseCover: "Choose cover",
    CoverLabel: "Book cover",
    SplitElementLabel: "Style name for splitting into parts",
    IsbnSourcePagesLabel: "ISBN source for pagination",
    LoginButton: "Log in",
    LogoutButton: "Log out",
    ReallyLogout: "Do you really want to log out?",
    CloseButton: "Close",
    isLogged: "",
    isNotedLogged: "Not logged in",
    LoginDialogTitle: "Login to Simon app",
    LoginDialogFormInvalid: "Enter required information.",
    LoginDialogInvalidCredentials: "Incorrect username or password.",
    LoginDialogDisabled: "This account does not have permission to log in to the system.",
    LoginDialogLockedOut: "Your account has been temporarily locked due to too many unsuccessful logins. Wait until the account is automatically unlocked and try logging in again.",
    RequestToServerFailed: "Failed to connect the server.",
    LoginDialogUsername: "Username",
    LoginDialogPassword: "Password",
    LoginFailed: "Login failed. Check entered credentials.",
    LoginDialogCloseButton: "Close",
    LoginDialogLoginButton: "Login",
    ConfirmNotAnchoredImagesEPUB: "The document contains unanchored images. We recommend anchoring them before exporting. Do you want to continue exporting to EPUB?",
    ConfirmNotAnchoredImagesSendToServer: "The document contains unanchored images. We recommend anchoring them before sending. Do you want to continue sending to the Simon app?",
    NoActiveDocument: "You must first open a document.",
    ExportSettingsDialogTitle: "Export settings",
    ExportSettingsDialogCloseButton: "Close",
    ExportSettingsDialogSubmit: "OK",
    CoverImageIsLoading: "Cover is loading...",
    UnknownError: "Unknown error",
    ExportFailed: "Export to epub file failed.",
    CannotGetFileForSaving: "Failed to get file for saving",
    CannotCreateTemporaryFileOrFolder: "Failed to create temporary file or folder",
    CannotReadTemporaryFile: "Failed to open the finished epub file",
    LoginExpired: "Session probably expired. Please log in again.",
    SendFailedLoginExpired: "Sending to the Simon app failed. Session probably expired. Please log in again.",
    SendFailed: "Sending the file to the Simon app failed.",
    SendSuccess: "The file was successfully sent to the Simon app."
}